### ISSUE TITLE
fix typo in mergify.yml

### ISSUE THREAD

**Issue by agarwal-akash** [twilio-labs/open-pixel-art#907]
```
actions:
      comment:
        message: 'This PR touches more than one file and has to be [revied] manually. @dkundel'
      label:
        add:
          - 'needs-review'
```
